language: node_js
node_js:
  - "6"
  - "7"
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database lego_test;' -U postgres
after_script:
  - npm run coverage
  - npm run coveralls
env:
  - DATABASE_URL=postgres://postgres@localhost/lego_test LEGO_DISABLE_SSL=true
